services:

  db:
    image: postgres:16.3-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - scrum_platform_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    image: keycloak:latest
    container_name: keycloak
    depends_on:
      - db
    environment:
      - KC_HTTP_PORT=${KC_PORT}
      - KC_DB_URL=jdbc:postgresql://${KC_DB_HOST}:5432/${KC_DB_NAME}
      - KC_DB_USERNAME=${KC_DB_USER}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KEYCLOAK_ADMIN=${KC_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
    ports:
      - "${KC_PORT}:${KC_PORT}"

volumes:
  scrum_platform_data:
